name: Integration Tests
on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        env:
            REMOVED: ${{ secrets.REMOVED }}
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 9.4.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "pnpm"

            - name: Clean up
              run: pnpm clean

            - name: Install dependencies
              run: pnpm install -r

            - name: Build packages
              run: pnpm build

            - name: Check for API key
              run: |
                  if [ -z "$REMOVED" ]; then
                      echo "Error: REMOVED is not set."
                      exit 1
                  fi

            - name: Run integration tests
              run: pnpm run integrationTests
